### ISSUE TITLE
TODO: backlinks to source URIs in output

### ISSUE THREAD

**Issue by handelaar** [handelaar/an2pw#4]
- [ ] calculate how on earth the source site URIs are being calculated
- [ ] if it is predictable, add them to every output element
- [ ] if it is not predictable, close this issue
