### ISSUE TITLE
TODO: Concatenate all cttees for a day into one publicwhip output file

### ISSUE THREAD

**Issue by handelaar** [handelaar/an2pw#7]
- [ ] feed arbitrary list of >=1 files into parser
- [ ] parser loadfile should check if passed var is an array; if yes, they're committees (document this)
- [ ] if 'committees' flag set, demote all of each heading in all AN files by one level
- [ ] move cttee prelude matter under artificial subheading 'prelude' as with Dáil
- [ ] decide whether to merge AN files in memory before parsing or to walk through them all separately
